# Generated by Django 4.2.6 on 2023-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('top_genre', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('dur', models.IntegerField(default=0)),
                ('pop', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Cancion',
            },
        ),
    ]
