# Generated by Django 5.0.2 on 2024-03-28 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('track_id', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('danceability', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('energy', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('key', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('loudness', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('mode', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('speechiness', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('acousticness', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('instrumentalness', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('liveness', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('valence', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('tempo', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('time_signature', models.DecimalField(decimal_places=6, max_digits=50, null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None)),
            ],
            options={
                'db_table': 'cancion',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('songId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
