# Generated by Django 5.0.2 on 2024-03-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='songId',
        ),
    ]
