# Generated by Django 4.2.6 on 2024-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('songId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
