# Generated by Django 5.0.2 on 2024-03-03 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0002_remove_cancion_songid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='cancion',
            name='speechiness',
            field=models.IntegerField(null=True),
        ),
    ]
