# Generated by Django 5.0.3 on 2024-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0003_alter_cancion_acousticness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='duration_ms',
            field=models.IntegerField(null=True),
        ),
    ]
