# Generated by Django 5.0.2 on 2024-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0003_cancion_genres_cancion_speechiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
