# Generated by Django 5.0.2 on 2024-03-04 17:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0004_alter_cancion_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='acousticness',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='danceability',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duration_ms',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='energy',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='instrumentalness',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='key',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='liveness',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='loudness',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='mode',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='speechiness',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='tempo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='time_signature',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='valence',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
