# Generated by Django 5.0.2 on 2024-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0005_alter_cancion_acousticness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='key',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='mode',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
    ]
