# Generated by Django 5.0.2 on 2024-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.IntegerField()),
                ('email', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
