# Generated by Django 5.0.2 on 2024-02-14 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaPrincipal', '0002_rating'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.IntegerField()),
                ('playlistName', models.TextField(max_length=200)),
                ('listaCanciones', models.ManyToManyField(to='paginaPrincipal.cancion')),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='playlists',
            field=models.ManyToManyField(to='usuarios.playlist'),
        ),
    ]
