# Generated by Django 5.0.2 on 2024-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_favoritos_playlist_usuario_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='userName',
            field=models.TextField(),
        ),
    ]
