# Generated by Django 4.2.6 on 2023-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('top_genre', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('bpm', models.IntegerField()),
                ('nrgy', models.IntegerField()),
                ('dnce', models.IntegerField()),
                ('dB', models.IntegerField()),
                ('live', models.IntegerField()),
                ('val', models.IntegerField()),
                ('dur', models.IntegerField()),
                ('acous', models.IntegerField()),
                ('spch', models.IntegerField()),
                ('pop', models.IntegerField()),
            ],
            options={
                'db_table': 'cancion',
            },
        ),
    ]
